### ISSUE TITLE
/portfolio Page is not accessible and broken

### ISSUE THREAD

**Issue by smooth1884** [sw-dao/dApp-frontend#11]
Looks like a Token page (even has the "Add token to Metamask" Button).

**Comment by Peter-Flynn** [comment]
The portfolio page is apparently functioning on the version available before the move to Polygon. May be in a state where we can get it working again without much work.

**Comment by smooth1884** [comment]
Ahh ok ill check it out

**Comment by Peter-Flynn** [comment]
Gonna move discussion to here: #16.
