### ISSUE TITLE
Re-enable/Fix Portfolio Page

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#16]
**Sender**: smooth1884@gmail.com
**Taken at**: https://stage-dot-sw-dao.ey.r.appspot.com/portfolio
**Fields**:
- Which feature needs to be added or changed?: Fix i
- What problem would this solve?: Its a hidden page and doesn&#39;t worrk
- Discord Username: Smooth1884@384
**Screenshot comments**:
1: Portfolio Page is Broken

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/e49223a4-2a1d-4326-9266-26f98184f88a-annotated_3b76d84b-d19f-481e-af7f-5b6d906922bb.png?etag=4489ba73d33d50260b8d9dcef7632438)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/e49223a4-2a1d-4326-9266-26f98184f88a-annotated_3b76d84b-d19f-481e-af7f-5b6d906922bb.png?etag=4489ba73d33d50260b8d9dcef7632438)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1750x962
**Labels**: Feature Revision
**[Open #7 in Usersnap](https://app.usersnap.com/l/feedback/e1f36b69-4504-42d4-93f7-5b0217d5dbc5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Peter-Flynn** [comment]
The original portfolio page, from before the Polygon migration, worked just fine. Hopefully the broken piece is small in scope.
