### ISSUE TITLE
SWEYF Page - Repetitive Text

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#20]
**Sender**: itassicker@gmail.com
**Taken at**: http://app.swdao.org/product/SWEYF
**Fields**:
- Which feature needs to be added or changed?: Doubled up on text
- What problem would this solve?: The &#39;Risk Management&#39; section of the page needs to have every detail screaming &#39;professionalism&#39; for people to trust us.
- Discord Username: bananabread#2169

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/2b97733d-9126-40c9-87af-c027130e41c4-annotated_9b62118f-27bc-4c88-917a-164262ee0f69.png?etag=ffdd20e7cf10b21c58224632489099a4)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/2b97733d-9126-40c9-87af-c027130e41c4-annotated_9b62118f-27bc-4c88-917a-164262ee0f69.png?etag=ffdd20e7cf10b21c58224632489099a4)*

**Browser**: Firefox 100 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x927
**Labels**: Low Priority
**[Open #11 in Usersnap](https://app.usersnap.com/l/feedback/f7ced930-134d-4410-ae78-cd1c499da662?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by smooth1884** [comment]
Closing with: https://github.com/sw-dao/dApp-frontend/commit/5b3d420d3ff27df35f92dc0cc9bb4f224118e051
