### ISSUE TITLE
Auto-remove Auto-fill Zeros

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#21]
**Sender**: smooth1884@gmail.com
**Taken at**: http://app.swdao.org/product/PEI
**Fields**:
- Which feature needs to be added or changed?: &#34;0&#34; not disappearing automatically
- What problem would this solve?: no need to manually delete it.

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/3fe76b20-2780-4882-ac90-44066555d58d-annotated_48b2d847-9ef6-4eb0-a62b-46752fd555e9.png?etag=0b313ecce7ceb72a06a4d42e7928b3b6)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/3fe76b20-2780-4882-ac90-44066555d58d-annotated_48b2d847-9ef6-4eb0-a62b-46752fd555e9.png?etag=0b313ecce7ceb72a06a4d42e7928b3b6)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1750x962
**Labels**: Feature Revision
**[Open #12 in Usersnap](https://app.usersnap.com/l/feedback/e63cff3e-dc1a-4834-bca0-1018e059d234?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Peter-Flynn** [comment]
Definitely annoying.

**Comment by smooth1884** [comment]
Check it out, now it's muuuch better :) https://github.com/sw-dao/dApp-frontend/commit/911f5d896fd59d53be348d557e21ee7603017b55
