### ISSUE TITLE
[feedback] SWAP $ value changes

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#26]
**Sender**: sha256@swdao.org
**Taken at**: https://app.swdao.org/
**Fields**:
- Which feature needs to be added or changed?: SWAP $ value changes
- What problem would this solve?: ~30 seconds after page load, this initial load value of 44.77 corrects to the accurate pricing of ~49
- Discord Username: SHA256or₿UST | SW DAO#0459

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/13b5aefb-4773-4bd3-b3ec-895e35b5f7b3-annotated_b826ba2b-785c-4456-b75c-4ad1bdc6fb98.png?etag=525a22162d27ef654f847c5c6a37c4a2)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/13b5aefb-4773-4bd3-b3ec-895e35b5f7b3-annotated_b826ba2b-785c-4456-b75c-4ad1bdc6fb98.png?etag=525a22162d27ef654f847c5c6a37c4a2)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 2560x1440
**Browser size**: 1760x1279
**Labels**: Medium Priority
**[Open #17 in Usersnap](https://app.usersnap.com/l/feedback/c36dcde9-1781-4227-8ab6-efe1f9c89be2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Peter-Flynn** [comment]
I suspect what we're seeing is that the "daily" data loads well before the "minutes" data. The entire front-end pricing mechanism needs to be rebuilt from scratch, so for now I'm closing with "won't fix". It's a problem that will get solved with the rewrite.
