### ISSUE TITLE
Buy Button Hover Text

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#28]
**Sender**: alex@swdao.org
**Taken at**: https://www.app.swdao.org/token
**Fields**:
- Which feature needs to be added or changed?: Hovering over Buy button
- What problem would this solve?: Let&#39;s rename &#34;Send to contract&#34; to &#34;Purchase tokens&#34;

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/9be0f656-0f34-41de-9616-ebc0457bc556-annotated_254d36cd-7f4d-4788-9b81-9b54aee5d25d.png?etag=eb28d0243fda24585b0effde4ba33448)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/9be0f656-0f34-41de-9616-ebc0457bc556-annotated_254d36cd-7f4d-4788-9b81-9b54aee5d25d.png?etag=eb28d0243fda24585b0effde4ba33448)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1512x982
**Browser size**: 1512x869
**[Open #19 in Usersnap](https://app.usersnap.com/l/feedback/e35f71d4-a609-4c73-b2c5-dc68da589112?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Peter-Flynn** [comment]
Fixed with: 977d9f7a18975d2a0624a72395eed2e9c1f292f0.
