### ISSUE TITLE
Safari "Token Choice" Menu Overlay

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#37]
**Sender**: sha256@swdao.org
**Taken at**: http://app.swdao.org/token
**Fields**:
- Which feature needs to be added or changed?: MATIC Button Overlay
- What problem would this solve?: MATIC button on mobile page load is auto selected with large pop out - clicking it automatically resets it back to proper format

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/e2d588a0-45b2-4ec3-801b-864124a10a8c-annotated_aaaeef81-6d1c-4876-abe7-b3e121030ae1.png?etag=f91bf825323e5617189f9aa4fe959012)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/e2d588a0-45b2-4ec3-801b-864124a10a8c-annotated_aaaeef81-6d1c-4876-abe7-b3e121030ae1.png?etag=f91bf825323e5617189f9aa4fe959012)*

**Browser**: Safari 15 (iOS)
**Screen size**: 390x844
**Browser size**: 390x658
**Labels**: Low Priority
**[Open #27 in Usersnap](https://app.usersnap.com/l/feedback/cbce95e3-d9cb-4e7a-a532-3728879d7263?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Peter-Flynn** [comment]
Unable to replicate on my end. May be Safari-only issue? @smooth1884, do you have an iPhone?

**Comment by smooth1884** [comment]
Chrome on iPhone: 
![image](https://user-images.githubusercontent.com/20353333/171076538-c958d31f-769a-49f5-8777-235ef475b796.png)
Safari on iPhone:
![image](https://user-images.githubusercontent.com/20353333/171076630-f70dc75a-2413-4cd2-981b-e62ea89da29b.png)

**Comment by Peter-Flynn** [comment]
How's Safari look?

**Comment by smooth1884** [comment]
Ah I see it's when it's not yet selected. This is what it looks like to me. Reloaded the page. No issues

![image](https://user-images.githubusercontent.com/20353333/171076766-391059e6-93a9-4fa4-bbe1-c274d5f00d5a.png)

**Comment by Peter-Flynn** [comment]
Just noticed that you already posted both browsers. So you can't replicate it? Very weird.

**Comment by smooth1884** [comment]
SWD does look weird on the Sell tab

![image](https://user-images.githubusercontent.com/20353333/171077287-b4555a05-fe97-47b4-bd07-d37ec64a28da.png)
