### ISSUE TITLE
[feedback] Chart Timeframe and change not properly represented.

### ISSUE THREAD

**Issue by SHA256orBUST** [sw-dao/dApp-frontend#47]
**Sender**: cryptokraxis@gmail.com
**Taken at**: https://app.swdao.org/?sort=-change&period=1W
**Fields**:
- Which feature needs to be added or changed?: Chart Timeframe and change not properly represented.
- What problem would this solve?: The Change column does not change or show different numbers when a different timeframe is selected (1 day, 1 week, 1 year, etc.). 

Is the change column simply the past 24 hours? If it doesn&#39;t change with the chart then it should clearly state what timeline it is on.

This impacts trust and professionalism of the product.
- Discord Username: Kraxis#3242

![SCREENSHOT](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/5bb3695e-accb-453d-84c9-b6b49c3d7f3a-annotated_1682a2df-cd98-4ec5-af38-6079e4f749b2.png?etag=021204480340a1e42c0c69389afb8d94)
*[Download original image](https://resources.usersnap.com/company/3a4c28b7-3b31-478c-a2db-d92b943c79b8/datapoint_screenshot/5bb3695e-accb-453d-84c9-b6b49c3d7f3a-annotated_1682a2df-cd98-4ec5-af38-6079e4f749b2.png?etag=021204480340a1e42c0c69389afb8d94)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1283
**Labels**: High Priority
**[Open #35 in Usersnap](https://app.usersnap.com/l/feedback/ad5f695b-8ffc-41ae-91af-59c6a4c81bf4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by smooth1884** [comment]
https://github.com/sw-dao/dApp-frontend/commit/1306ca0af7c8aeb75319f3349abff4be06322170
